# Site Settings
theme: bulma-clean-theme
title: Eclipsta Studio
tagline:
email: 
description: Onde a luz encontra a forma.
baseurl: ""
url: ""
permalink: pretty
favicon: "/img/Eclipsta.svg"
gh_sponsor: 
#hide_share_buttons: true
fixed_navbar: top
direction: ltr #ltr, rtl, auto
force_theme: dark
langs:
  - pt
  - en
lang: pt
locale: pt_BR
timezone: America/Sao_Paulo

paginate: 10
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->

disqus:
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname:

include: [llms.txt]

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - jstudio3design
  - .vscode/
  - .github/


livereload: true

sass:
  style: compressed
  source_dir: _sass
  quiet_deps: true
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Eclipsta Studio"
      layout: post
      image:
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: 
    show_sidebar: false

social:
  - facebook: #Add your Facebook
  - twitter: #Add your Twitter
  - google-plus: #Add your Google+
  - github: #Add your GitHub
  - instagram: #Add your Instagram
  - linkedin: #Add your LinkedIn
  - pinterest: #Add your Pinterest
  - youtube: #Add your YouTube
  - behance: #Add your Behance
  - dribbble: #Add your Dribbble
  - whatsapp: #Add your WhatsApp
  - telegram: #Add your Telegram
  - twitch: #Add your Twitch
  - discord: #Add your Discord
  - reddit: #Add your Reddit
  - skype: #Add your Skype
  - stack-overflow: #Add your Stack Overflow
  - medium: #Add your Medium
  - spotify: #Add your Spotify
  - soundcloud: #Add your SoundCloud
  - tumblr: #Add your Tumblr
  - flickr: #Add your Flickr
  - vimeo: #Add your Vimeo
  - rss: #/feed.xml
  - email: #mailto:
